[project]
name = "odoo-addons-sygel-technology-sy-project"
version = "18.0.20260202.3"
dependencies = [
    "odoo-addon-duplicate_project_task_timesheet==18.0.*",
    "odoo-addon-project_coordinator==18.0.*",
    "odoo-addon-project_internal_note==18.0.*",
    "odoo-addon-project_odoo_version==18.0.*",
    "odoo-addon-project_subtask_default_display_project==18.0.*",
    "odoo-addon-project_task_description_template_section==18.0.*",
    "odoo-addon-project_task_identification==18.0.*",
    "odoo-addon-project_task_show_project_manager==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
