[project]
name = "odoo-addons-sygel-technology-sy-project"
version = "18.0.20260122.0"
dependencies = [
    "odoo-addon-project_coordinator==18.0.*",
    "odoo-addon-project_internal_note==18.0.*",
    "odoo-addon-project_task_identification==18.0.*",
    "odoo-addon-project_task_show_project_manager==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
